---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-dojo-report-operator
  namespace: security-tools
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: trivy-dojo-report-operator
  template:
    metadata:
      labels:
        application: trivy-dojo-report-operator
    spec:
      serviceAccountName: trivy-dojo-report-account
      containers:
      - name: trivy-dojo-report-operator
        image: ghcr.io/telekom-mms/docker-trivy-dojo-operator:latest
        env:
        - name: DEFECT_DOJO_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: defect-dojo-api-credentials
              optional: false
        - name: DEFECT_DOJO_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: defect-dojo-api-credentials
              optional: false
        - name: DEFECT_DOJO_ACTIVE
          value: "true"
        - name: DEFECT_DOJO_VERIFIED
          value: "false"
        - name: DEFECT_DOJO_CLOSE_OLD_FINDINGS
          value: "false"
        - name: DEFECT_DOJO_CLOSE_OLD_FINDINGS_PRODUCT_SCOPE
          value: "false"
        - name: DEFECT_DOJO_PUSH_TO_JIRA
          value: "false"          
        - name: DEFECT_DOJO_MINIMUM_SEVERITY
          value: "Low"
        - name: DEFECT_DOJO_AUTO_CREATE_CONTEXT
          value: "true"
        - name: DEFECT_DOJO_DEDUPLICATION_ON_ENGAGEMENT
          value: "true"
        - name: DEFECT_DOJO_DO_NOT_REACTIVATE
          value: "true"
        - name: DEFECT_DOJO_GROUP_BY
          value: "component-name"
        - name: DEFECT_DOJO_ENVIRONMENT
          value: "Lab"
        - name: DEFECT_DOJO_PRODUCT_TYPE_NAME
          value: "Research and Development"
        - name: DEFECT_DOJO_PRODUCT_NAME
          value: "k8s-dojo-operator-try-01"          


        resources: {}