apiVersion: v1
data:
  url: aHR0cDovL2RlZmVjdGRvam8uazhzLjE2OC4xOTYuOTQuMTEubmlwLmlv
  api-key: NjMzNjc1ZTJhMWY2N2QwMzVjMDNiN2M4ZjU2MThlYjNiYjIxZGJhZQ==
kind: Secret
metadata:
  name: defect-dojo-api-credentials
  namespace: security-tools
type: Opaque
